version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /dev:/dev:ro
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
    depends_on:
      - redis
  redis:
    image: redis:alpine
