version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /dev:/dev:ro
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
    depends_on:
      - redis
  redis:
    image: redis:alpine

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: node node_server.js
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
      - ./frontend/build:/app/frontend/build
    depends_on:
      - web
